sudo: false
language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install flake8
  - pip install -r requirements.txt
script:
  - flake8 quandl
  - python -W always setup.py -q test
cache:
  directories:
    - $HOME/.cache/pip
    - ./.eggs
    - ./quandl.egg-info